// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// SSE streaming chat
				Method:  http.MethodPost,
				Path:    "/chat/stream",
				Handler: ChatStreamHandler(serverCtx),
			},
			{
				// Get preset prompts
				Method:  http.MethodGet,
				Path:    "/presets",
				Handler: GetPresetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
