// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type ChatStreamReq struct {
	Model        ModelConfig   `json:"model"`
	SystemPrompt string        `json:"system_prompt,optional"`
	Messages     []ChatMessage `json:"messages"`
	Temperature  float64       `json:"temperature,optional,default=0.8"`
	MaxTokens    int           `json:"max_tokens,optional,default=2048"`
}

type ModelConfig struct {
	Name    string `json:"name"`
	ApiKey  string `json:"api_key"`
	BaseUrl string `json:"base_url"`
}

type PresetPrompt struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

type PresetsResp struct {
	Presets []PresetPrompt `json:"presets"`
}
